// <auto-generated />
namespace T2NSHOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit_reviewProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_reviewProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202312011415185_edit_reviewProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
