// <auto-generated />
namespace T2NSHOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_codeInShopingCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_codeInShopingCart));
        
        string IMigrationMetadata.Id
        {
            get { return "202311251747090_add_codeInShopingCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
