// <auto-generated />
namespace T2NSHOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_isdeteleInShopingCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isdeteleInShopingCart));
        
        string IMigrationMetadata.Id
        {
            get { return "202311251743224_add_isdeteleInShopingCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
